export interface Recipe {
  id: string;
  name: string;
  proteinG: number;
  caloriesKcal: number;
  prepTimeMin: number;
  difficulty: "easy" | "medium" | "hard";
  ingredients: { item: string; amount: string }[];
  steps: string[];
  tags: string[];
}

export const RECIPES: Recipe[] = [
  // ── South Asian ──────────────────────────────────────────────────────────────
  {
    id: "chicken-tikka-masala",
    name: "Chicken tikka masala with rice",
    proteinG: 45,
    caloriesKcal: 620,
    prepTimeMin: 30,
    difficulty: "medium",
    ingredients: [
      { item: "Chicken breast", amount: "200g" },
      { item: "Basmati rice", amount: "80g dry" },
      { item: "Tikka masala sauce", amount: "150g" },
      { item: "Greek yogurt", amount: "2 tbsp" },
      { item: "Garlic & ginger paste", amount: "1 tsp" },
    ],
    steps: [
      "Marinate chicken in yogurt, garlic-ginger paste, and tikka spices for 10 minutes.",
      "Cook rice according to package instructions.",
      "Pan-fry chicken on high heat until lightly charred, about 6 min each side.",
      "Add tikka masala sauce, reduce heat, simmer 10 minutes.",
      "Serve chicken and sauce over rice.",
    ],
    tags: ["south-asian", "high-protein", "meal-prep"],
  },
  {
    id: "lamb-keema-chapatti",
    name: "Lamb keema with chapatti",
    proteinG: 38,
    caloriesKcal: 580,
    prepTimeMin: 25,
    difficulty: "medium",
    ingredients: [
      { item: "Lean lamb mince", amount: "150g" },
      { item: "Chapatti (2 medium)", amount: "2" },
      { item: "Onion, diced", amount: "½" },
      { item: "Tomatoes, chopped", amount: "2 medium" },
      { item: "Peas", amount: "50g" },
      { item: "Cumin, coriander, garam masala", amount: "1 tsp each" },
    ],
    steps: [
      "Brown the lamb mince in a dry pan over high heat, breaking it up.",
      "Add onions and cook until softened, about 5 minutes.",
      "Stir in spices and tomatoes, cook 5 minutes.",
      "Add peas and cook 3 more minutes. Season to taste.",
      "Serve with warm chapattis.",
    ],
    tags: ["south-asian", "high-protein"],
  },
  {
    id: "paneer-spinach-curry",
    name: "Paneer and spinach curry",
    proteinG: 24,
    caloriesKcal: 380,
    prepTimeMin: 20,
    difficulty: "easy",
    ingredients: [
      { item: "Paneer", amount: "150g" },
      { item: "Spinach", amount: "200g" },
      { item: "Onion, chopped", amount: "1 small" },
      { item: "Cream", amount: "2 tbsp" },
      { item: "Garlic-ginger paste", amount: "1 tsp" },
      { item: "Cumin seeds, garam masala", amount: "1 tsp each" },
    ],
    steps: [
      "Cube paneer and lightly pan-fry until golden. Set aside.",
      "Sauté onion with cumin seeds until golden.",
      "Add garlic-ginger paste and cook 1 minute.",
      "Add spinach and cook until wilted. Blend or mash roughly.",
      "Add paneer, cream, garam masala. Simmer 5 minutes.",
    ],
    tags: ["south-asian", "vegetarian", "high-protein"],
  },
  {
    id: "dal-tadka-brown-rice",
    name: "Dal tadka with brown rice",
    proteinG: 22,
    caloriesKcal: 450,
    prepTimeMin: 35,
    difficulty: "medium",
    ingredients: [
      { item: "Red lentils (masoor dal)", amount: "120g dry" },
      { item: "Brown rice", amount: "80g dry" },
      { item: "Onion, tomato, garlic", amount: "½ each" },
      { item: "Ghee or oil", amount: "1 tbsp" },
      { item: "Cumin, mustard seeds, turmeric, chilli", amount: "1 tsp each" },
    ],
    steps: [
      "Boil lentils with water, turmeric, and salt until soft (20 min).",
      "Cook brown rice separately per instructions.",
      "Heat ghee, add mustard and cumin seeds until they pop.",
      "Add onion, garlic, and tomato; cook until softened.",
      "Pour tadka over lentils and simmer 5 minutes. Serve with rice.",
    ],
    tags: ["south-asian", "vegetarian", "high-protein"],
  },
  {
    id: "egg-curry",
    name: "Egg curry (3 eggs)",
    proteinG: 28,
    caloriesKcal: 360,
    prepTimeMin: 20,
    difficulty: "easy",
    ingredients: [
      { item: "Eggs", amount: "3 large" },
      { item: "Onion, diced", amount: "1 medium" },
      { item: "Tomato sauce or passata", amount: "150ml" },
      { item: "Oil", amount: "1 tbsp" },
      { item: "Curry powder, turmeric, chilli", amount: "1 tsp each" },
    ],
    steps: [
      "Hard-boil eggs (10 minutes), peel and halve them.",
      "Sauté onion in oil until golden.",
      "Add spices and cook 1 minute, then add tomato sauce.",
      "Simmer sauce 8 minutes. Add halved eggs.",
      "Cook 3 more minutes and serve.",
    ],
    tags: ["south-asian", "high-protein", "quick"],
  },
  {
    id: "chicken-biryani",
    name: "Chicken biryani",
    proteinG: 42,
    caloriesKcal: 680,
    prepTimeMin: 45,
    difficulty: "hard",
    ingredients: [
      { item: "Chicken thighs, boneless", amount: "250g" },
      { item: "Basmati rice", amount: "100g dry" },
      { item: "Yogurt", amount: "3 tbsp" },
      { item: "Onion, sliced", amount: "1 large" },
      { item: "Whole spices (cardamom, cloves, bay leaf)", amount: "1 tsp each" },
      { item: "Biryani spice mix", amount: "2 tsp" },
    ],
    steps: [
      "Marinate chicken in yogurt and biryani spice for 20 minutes.",
      "Fry sliced onions until dark and crispy. Set aside.",
      "Par-boil rice (70% cooked) with whole spices.",
      "Brown marinated chicken in the same pan, 5 min per side.",
      "Layer rice over chicken, top with crispy onions, seal and steam 15 minutes.",
    ],
    tags: ["south-asian", "high-protein", "meal-prep"],
  },
  {
    id: "seekh-kebabs",
    name: "Seekh kebabs (×4)",
    proteinG: 36,
    caloriesKcal: 380,
    prepTimeMin: 20,
    difficulty: "medium",
    ingredients: [
      { item: "Lean lamb or beef mince", amount: "200g" },
      { item: "Onion, grated", amount: "¼" },
      { item: "Coriander, green chilli, ginger", amount: "to taste" },
      { item: "Gram flour (besan)", amount: "1 tbsp" },
      { item: "Cumin, coriander powder, garam masala", amount: "1 tsp each" },
    ],
    steps: [
      "Combine mince, onion, spices, and gram flour. Mix well and rest 10 minutes.",
      "Divide into 4 portions. Mould around skewers in sausage shapes.",
      "Cook under a hot grill or on a griddle pan, 4 min per side.",
      "Serve with mint chutney and lemon wedges.",
    ],
    tags: ["south-asian", "high-protein", "quick"],
  },
  {
    id: "chana-chicken-stew",
    name: "Chana and chicken stew",
    proteinG: 34,
    caloriesKcal: 480,
    prepTimeMin: 30,
    difficulty: "medium",
    ingredients: [
      { item: "Chicken breast, diced", amount: "150g" },
      { item: "Chickpeas, cooked", amount: "200g (1 tin)" },
      { item: "Onion, tomato, garlic", amount: "½ each" },
      { item: "Spinach or kale", amount: "50g" },
      { item: "Cumin, coriander, turmeric, paprika", amount: "1 tsp each" },
    ],
    steps: [
      "Brown chicken in a little oil. Remove and set aside.",
      "Sauté onion and garlic until soft. Add spices and tomato.",
      "Add chickpeas and 200ml water. Simmer 10 minutes.",
      "Return chicken to the pan, stir in spinach until wilted.",
      "Season and serve.",
    ],
    tags: ["south-asian", "high-protein", "meal-prep"],
  },

  // ── General high-protein ─────────────────────────────────────────────────────
  {
    id: "greek-yogurt-protein-bowl",
    name: "Greek yogurt protein bowl",
    proteinG: 35,
    caloriesKcal: 410,
    prepTimeMin: 5,
    difficulty: "easy",
    ingredients: [
      { item: "Full-fat Greek yogurt", amount: "250g" },
      { item: "Whey protein powder", amount: "1 scoop (30g)" },
      { item: "Mixed berries", amount: "80g" },
      { item: "Granola", amount: "30g" },
      { item: "Honey", amount: "1 tsp" },
    ],
    steps: [
      "Mix whey powder into Greek yogurt until smooth.",
      "Top with berries and granola.",
      "Drizzle with honey and serve immediately.",
    ],
    tags: ["high-protein", "quick", "no-cook"],
  },
  {
    id: "tuna-avocado-wrap",
    name: "Tuna and avocado wrap",
    proteinG: 38,
    caloriesKcal: 480,
    prepTimeMin: 8,
    difficulty: "easy",
    ingredients: [
      { item: "Tuna in spring water", amount: "185g tin" },
      { item: "Large wholemeal wrap", amount: "1" },
      { item: "Avocado", amount: "½" },
      { item: "Lettuce, tomato", amount: "handful each" },
      { item: "Lemon juice, black pepper", amount: "to taste" },
    ],
    steps: [
      "Drain tuna and flake with a fork.",
      "Mash avocado with lemon juice and seasoning.",
      "Spread avocado over wrap, top with tuna, lettuce, and tomato.",
      "Roll tightly and slice in half.",
    ],
    tags: ["high-protein", "quick", "no-cook"],
  },
  {
    id: "chicken-rice-meal-prep",
    name: "Chicken and rice meal prep",
    proteinG: 52,
    caloriesKcal: 620,
    prepTimeMin: 30,
    difficulty: "easy",
    ingredients: [
      { item: "Chicken breast", amount: "250g" },
      { item: "Basmati or jasmine rice", amount: "100g dry" },
      { item: "Broccoli or green beans", amount: "150g" },
      { item: "Olive oil, garlic powder, paprika", amount: "1 tbsp / 1 tsp / 1 tsp" },
    ],
    steps: [
      "Season chicken with olive oil, garlic powder, paprika, salt.",
      "Cook rice per instructions.",
      "Bake or pan-fry chicken (20 min at 200°C or 12 min in pan).",
      "Steam vegetables for 4 minutes.",
      "Portion into containers: rice, chicken, vegetables.",
    ],
    tags: ["high-protein", "meal-prep", "quick"],
  },
  {
    id: "salmon-sweet-potato",
    name: "Salmon with sweet potato",
    proteinG: 40,
    caloriesKcal: 540,
    prepTimeMin: 30,
    difficulty: "easy",
    ingredients: [
      { item: "Salmon fillet", amount: "200g" },
      { item: "Sweet potato", amount: "200g" },
      { item: "Asparagus or green beans", amount: "100g" },
      { item: "Lemon, olive oil, dill", amount: "to taste" },
    ],
    steps: [
      "Cut sweet potato into cubes, toss with olive oil, roast at 200°C for 25 min.",
      "Season salmon with lemon, dill, and a little oil.",
      "Pan-fry salmon skin-side down 4 min, flip and cook 3 more.",
      "Steam asparagus 3 minutes.",
      "Plate and serve with lemon wedge.",
    ],
    tags: ["high-protein", "meal-prep"],
  },
  {
    id: "turkey-bolognese",
    name: "Turkey mince bolognese",
    proteinG: 44,
    caloriesKcal: 580,
    prepTimeMin: 30,
    difficulty: "easy",
    ingredients: [
      { item: "Lean turkey mince", amount: "200g" },
      { item: "Whole wheat pasta", amount: "80g dry" },
      { item: "Passata", amount: "200ml" },
      { item: "Onion, garlic, celery", amount: "½ each" },
      { item: "Italian herbs, olive oil", amount: "1 tsp / 1 tbsp" },
    ],
    steps: [
      "Cook pasta according to package; drain.",
      "Sauté onion, garlic, and celery in olive oil 5 minutes.",
      "Add turkey mince, break up, and brown.",
      "Add passata and herbs; simmer 15 minutes.",
      "Serve sauce over pasta.",
    ],
    tags: ["high-protein", "meal-prep"],
  },
  {
    id: "cottage-cheese-toast",
    name: "Cottage cheese toast (×2 slices)",
    proteinG: 28,
    caloriesKcal: 320,
    prepTimeMin: 5,
    difficulty: "easy",
    ingredients: [
      { item: "Thick wholegrain bread", amount: "2 slices" },
      { item: "Cottage cheese", amount: "200g" },
      { item: "Cherry tomatoes or cucumber", amount: "handful" },
      { item: "Black pepper, chilli flakes", amount: "to taste" },
    ],
    steps: [
      "Toast bread until golden.",
      "Spread cottage cheese generously over each slice.",
      "Top with cherry tomatoes or cucumber.",
      "Season with black pepper and chilli flakes.",
    ],
    tags: ["high-protein", "quick", "no-cook"],
  },
  {
    id: "egg-white-omelette",
    name: "Egg white omelette (4 eggs)",
    proteinG: 22,
    caloriesKcal: 180,
    prepTimeMin: 8,
    difficulty: "easy",
    ingredients: [
      { item: "Egg whites", amount: "4 (or 120ml carton)" },
      { item: "Spinach", amount: "50g" },
      { item: "Mushrooms, sliced", amount: "50g" },
      { item: "Low-fat cheddar", amount: "30g" },
      { item: "Spray oil, salt, pepper", amount: "to taste" },
    ],
    steps: [
      "Spray a non-stick pan and sauté mushrooms until golden.",
      "Add spinach and wilt for 1 minute.",
      "Pour in egg whites and cook on medium-low, tilting pan.",
      "Add cheese to one half, fold omelette over. Cook 1 more minute.",
      "Slide onto plate and serve.",
    ],
    tags: ["high-protein", "quick", "vegetarian"],
  },
  {
    id: "protein-overnight-oats",
    name: "Protein overnight oats",
    proteinG: 32,
    caloriesKcal: 420,
    prepTimeMin: 5,
    difficulty: "easy",
    ingredients: [
      { item: "Rolled oats", amount: "70g" },
      { item: "Protein powder (vanilla)", amount: "1 scoop (30g)" },
      { item: "Greek yogurt", amount: "100g" },
      { item: "Milk (any)", amount: "150ml" },
      { item: "Banana or berries", amount: "½ / handful" },
    ],
    steps: [
      "Combine oats, protein powder, yogurt, and milk in a jar.",
      "Mix well, ensuring no dry powder remains.",
      "Refrigerate overnight (or at least 4 hours).",
      "Top with fruit before eating.",
    ],
    tags: ["high-protein", "meal-prep", "no-cook"],
  },
  {
    id: "beef-veg-stir-fry",
    name: "Beef and vegetable stir fry",
    proteinG: 42,
    caloriesKcal: 520,
    prepTimeMin: 15,
    difficulty: "easy",
    ingredients: [
      { item: "Lean beef strips (sirloin)", amount: "200g" },
      { item: "Stir-fry veg mix (broccoli, peppers, snap peas)", amount: "200g" },
      { item: "Soy sauce, oyster sauce", amount: "1 tbsp each" },
      { item: "Garlic, ginger, sesame oil", amount: "1 tsp each" },
      { item: "Brown rice or noodles", amount: "80g dry" },
    ],
    steps: [
      "Cook rice or noodles per instructions.",
      "Heat wok until smoking. Flash-fry beef strips 2 minutes. Remove.",
      "Stir-fry vegetables in same wok 3-4 minutes.",
      "Return beef, add sauces, garlic, ginger. Toss 1 minute.",
      "Drizzle sesame oil, serve over rice or noodles.",
    ],
    tags: ["high-protein", "quick"],
  },
  {
    id: "mackerel-sourdough",
    name: "Mackerel on sourdough",
    proteinG: 30,
    caloriesKcal: 410,
    prepTimeMin: 5,
    difficulty: "easy",
    ingredients: [
      { item: "Smoked mackerel fillets", amount: "2 (approx 160g)" },
      { item: "Sourdough bread", amount: "2 thick slices" },
      { item: "Cream cheese or avocado", amount: "2 tbsp" },
      { item: "Lemon juice, capers, dill", amount: "to taste" },
    ],
    steps: [
      "Toast sourdough until golden.",
      "Spread cream cheese or mashed avocado on each slice.",
      "Flake mackerel over the top.",
      "Add capers, dill, and a squeeze of lemon.",
    ],
    tags: ["high-protein", "quick", "no-cook"],
  },
  // ── Extra 12 to reach 30 ─────────────────────────────────────────────────────
  {
    id: "prawn-stir-fry",
    name: "Prawn and edamame stir fry",
    proteinG: 36,
    caloriesKcal: 390,
    prepTimeMin: 12,
    difficulty: "easy",
    ingredients: [
      { item: "Prawns, raw", amount: "200g" },
      { item: "Edamame beans", amount: "100g" },
      { item: "Pak choi", amount: "150g" },
      { item: "Soy sauce, garlic, ginger", amount: "1 tbsp / 1 tsp / 1 tsp" },
      { item: "Sesame oil, chilli flakes", amount: "to taste" },
    ],
    steps: [
      "Stir-fry prawns in a hot wok 2 min per side until pink. Remove.",
      "Add pak choi and edamame, stir-fry 3 minutes.",
      "Return prawns, add soy sauce, garlic, ginger. Toss well.",
      "Drizzle sesame oil and serve.",
    ],
    tags: ["high-protein", "quick"],
  },
  {
    id: "turkey-stuffed-peppers",
    name: "Turkey stuffed peppers",
    proteinG: 38,
    caloriesKcal: 430,
    prepTimeMin: 40,
    difficulty: "medium",
    ingredients: [
      { item: "Bell peppers", amount: "2 large" },
      { item: "Turkey mince", amount: "200g" },
      { item: "Cooked quinoa", amount: "100g" },
      { item: "Tomato passata, onion, garlic", amount: "100ml / ½ / 1 clove" },
      { item: "Mixed herbs, cheese", amount: "1 tsp / 30g" },
    ],
    steps: [
      "Halve and deseed peppers. Place cut-side up in a baking dish.",
      "Brown turkey mince with onion and garlic.",
      "Mix in passata, quinoa, and herbs. Season.",
      "Fill peppers with the mixture, top with cheese.",
      "Bake at 190°C for 25 minutes.",
    ],
    tags: ["high-protein", "meal-prep"],
  },
  {
    id: "protein-pancakes",
    name: "Protein pancakes (×4)",
    proteinG: 34,
    caloriesKcal: 380,
    prepTimeMin: 15,
    difficulty: "easy",
    ingredients: [
      { item: "Rolled oats (blended to flour)", amount: "60g" },
      { item: "Protein powder", amount: "1 scoop (30g)" },
      { item: "Eggs", amount: "2" },
      { item: "Banana, mashed", amount: "1 medium" },
      { item: "Milk", amount: "60ml" },
    ],
    steps: [
      "Blend all ingredients until smooth.",
      "Heat a non-stick pan on medium, spray with oil.",
      "Pour ¼ of batter per pancake, cook 2 min until bubbles form.",
      "Flip and cook 1 more minute.",
      "Serve with Greek yogurt and fruit.",
    ],
    tags: ["high-protein", "quick", "vegetarian"],
  },
  {
    id: "sardine-pasta",
    name: "Sardine and tomato pasta",
    proteinG: 36,
    caloriesKcal: 530,
    prepTimeMin: 15,
    difficulty: "easy",
    ingredients: [
      { item: "Sardines in tomato sauce", amount: "2 tins (240g)" },
      { item: "Whole wheat pasta", amount: "80g dry" },
      { item: "Garlic, olive oil, capers", amount: "1 clove / 1 tbsp / 1 tsp" },
      { item: "Chilli flakes, parsley", amount: "to taste" },
    ],
    steps: [
      "Cook pasta per instructions; reserve 50ml pasta water.",
      "Sauté garlic in olive oil. Add sardines (with sauce) and capers.",
      "Break sardines up with a fork. Simmer 3 minutes.",
      "Toss with drained pasta, adding pasta water to loosen.",
      "Finish with chilli flakes and parsley.",
    ],
    tags: ["high-protein", "quick", "meal-prep"],
  },
  {
    id: "lentil-chicken-soup",
    name: "Lentil and chicken soup",
    proteinG: 40,
    caloriesKcal: 420,
    prepTimeMin: 35,
    difficulty: "easy",
    ingredients: [
      { item: "Chicken thighs, boneless", amount: "200g" },
      { item: "Red lentils", amount: "100g" },
      { item: "Carrot, onion, celery", amount: "1 each" },
      { item: "Chicken stock", amount: "600ml" },
      { item: "Cumin, paprika, bay leaf", amount: "1 tsp each" },
    ],
    steps: [
      "Dice chicken, vegetables. Sauté in pot until lightly browned.",
      "Add lentils, stock, and spices. Bring to a boil.",
      "Reduce heat and simmer 25 minutes until lentils are soft.",
      "Shred chicken with two forks in the pot.",
      "Adjust seasoning and serve.",
    ],
    tags: ["high-protein", "south-asian", "meal-prep"],
  },
  {
    id: "beef-burger-bowl",
    name: "Lean beef burger bowl",
    proteinG: 46,
    caloriesKcal: 520,
    prepTimeMin: 15,
    difficulty: "easy",
    ingredients: [
      { item: "Lean beef mince (5% fat)", amount: "200g" },
      { item: "Romaine lettuce", amount: "2 large leaves" },
      { item: "Cherry tomatoes, cucumber", amount: "100g / ½" },
      { item: "Red onion, pickle", amount: "¼ / 30g" },
      { item: "Burger sauce or Greek yogurt sauce", amount: "2 tbsp" },
    ],
    steps: [
      "Form mince into 2 patties, season with salt and pepper.",
      "Cook patties in a dry pan 4 min per side.",
      "Chop lettuce, tomatoes, cucumber, and onion into a bowl.",
      "Slice patties and add to bowl.",
      "Drizzle with sauce and add pickles.",
    ],
    tags: ["high-protein", "quick"],
  },
];
