// Shared Arc logo mark — a white upward arc on the dark (#0D0D12) brand
// background. Matches the PWA icon design generated by scripts/generate-icons.js.
export function ArcMark({ size = 28, className }: { size?: number; className?: string }) {
  return (
    <svg width={size} height={size} viewBox="0 0 64 64" fill="none" className={className}>
      <rect width="64" height="64" rx="14" fill="#0D0D12" />
      <path d="M10 46 Q32 14 54 46" stroke="#FFFFFF" strokeWidth="5.5" strokeLinecap="round" />
    </svg>
  );
}
