-- 002_seed_exercises.sql
-- Seed 100 exercises (is_custom = false, user_id = null)

INSERT INTO exercises (id, name, category, muscle_primary, muscle_secondary, equipment, is_custom, user_id) VALUES

-- BARBELL (20)
(gen_random_uuid(), 'Barbell Back Squat', 'barbell', 'quadriceps', ARRAY['glutes','hamstrings','core'], 'barbell', false, null),
(gen_random_uuid(), 'Barbell Deadlift', 'barbell', 'hamstrings', ARRAY['glutes','back','core'], 'barbell', false, null),
(gen_random_uuid(), 'Barbell Bench Press', 'barbell', 'chest', ARRAY['shoulders','triceps'], 'barbell', false, null),
(gen_random_uuid(), 'Barbell Overhead Press', 'barbell', 'shoulders', ARRAY['triceps','core'], 'barbell', false, null),
(gen_random_uuid(), 'Barbell Bent-Over Row', 'barbell', 'back', ARRAY['biceps','core'], 'barbell', false, null),
(gen_random_uuid(), 'Barbell Romanian Deadlift', 'barbell', 'hamstrings', ARRAY['glutes','back'], 'barbell', false, null),
(gen_random_uuid(), 'Barbell Hip Thrust', 'barbell', 'glutes', ARRAY['hamstrings','core'], 'barbell', false, null),
(gen_random_uuid(), 'Barbell Front Squat', 'barbell', 'quadriceps', ARRAY['glutes','core'], 'barbell', false, null),
(gen_random_uuid(), 'Barbell Sumo Deadlift', 'barbell', 'glutes', ARRAY['hamstrings','quadriceps'], 'barbell', false, null),
(gen_random_uuid(), 'Barbell Incline Bench Press', 'barbell', 'chest', ARRAY['shoulders','triceps'], 'barbell', false, null),
(gen_random_uuid(), 'Barbell Close-Grip Bench Press', 'barbell', 'triceps', ARRAY['chest','shoulders'], 'barbell', false, null),
(gen_random_uuid(), 'Barbell Upright Row', 'barbell', 'shoulders', ARRAY['biceps','traps'], 'barbell', false, null),
(gen_random_uuid(), 'Barbell Good Morning', 'barbell', 'hamstrings', ARRAY['glutes','back'], 'barbell', false, null),
(gen_random_uuid(), 'Barbell Lunge', 'barbell', 'quadriceps', ARRAY['glutes','hamstrings'], 'barbell', false, null),
(gen_random_uuid(), 'Barbell Pendlay Row', 'barbell', 'back', ARRAY['biceps','core'], 'barbell', false, null),
(gen_random_uuid(), 'Barbell Pause Squat', 'barbell', 'quadriceps', ARRAY['glutes','core'], 'barbell', false, null),
(gen_random_uuid(), 'Barbell Zercher Squat', 'barbell', 'quadriceps', ARRAY['glutes','core','biceps'], 'barbell', false, null),
(gen_random_uuid(), 'Barbell Shrug', 'barbell', 'back', ARRAY['shoulders'], 'barbell', false, null),
(gen_random_uuid(), 'Barbell Curl', 'barbell', 'biceps', ARRAY['forearms'], 'barbell', false, null),
(gen_random_uuid(), 'Barbell Skull Crusher', 'barbell', 'triceps', ARRAY['chest'], 'barbell', false, null),

-- DUMBBELL (20)
(gen_random_uuid(), 'Dumbbell Bench Press', 'dumbbell', 'chest', ARRAY['shoulders','triceps'], 'dumbbell', false, null),
(gen_random_uuid(), 'Dumbbell Bicep Curl', 'dumbbell', 'biceps', ARRAY['forearms'], 'dumbbell', false, null),
(gen_random_uuid(), 'Dumbbell Row', 'dumbbell', 'back', ARRAY['biceps','core'], 'dumbbell', false, null),
(gen_random_uuid(), 'Dumbbell Chest Fly', 'dumbbell', 'chest', ARRAY['shoulders'], 'dumbbell', false, null),
(gen_random_uuid(), 'Dumbbell Lunge', 'dumbbell', 'quadriceps', ARRAY['glutes','hamstrings'], 'dumbbell', false, null),
(gen_random_uuid(), 'Dumbbell Goblet Squat', 'dumbbell', 'quadriceps', ARRAY['glutes','core'], 'dumbbell', false, null),
(gen_random_uuid(), 'Dumbbell Shoulder Press', 'dumbbell', 'shoulders', ARRAY['triceps'], 'dumbbell', false, null),
(gen_random_uuid(), 'Dumbbell Lateral Raise', 'dumbbell', 'shoulders', ARRAY['traps'], 'dumbbell', false, null),
(gen_random_uuid(), 'Dumbbell Romanian Deadlift', 'dumbbell', 'hamstrings', ARRAY['glutes','back'], 'dumbbell', false, null),
(gen_random_uuid(), 'Dumbbell Tricep Kickback', 'dumbbell', 'triceps', ARRAY[]::text[], 'dumbbell', false, null),
(gen_random_uuid(), 'Dumbbell Hammer Curl', 'dumbbell', 'biceps', ARRAY['forearms'], 'dumbbell', false, null),
(gen_random_uuid(), 'Dumbbell Incline Press', 'dumbbell', 'chest', ARRAY['shoulders','triceps'], 'dumbbell', false, null),
(gen_random_uuid(), 'Dumbbell Step-Up', 'dumbbell', 'quadriceps', ARRAY['glutes','hamstrings'], 'dumbbell', false, null),
(gen_random_uuid(), 'Dumbbell Hip Thrust', 'dumbbell', 'glutes', ARRAY['hamstrings'], 'dumbbell', false, null),
(gen_random_uuid(), 'Dumbbell Rear Delt Fly', 'dumbbell', 'shoulders', ARRAY['back'], 'dumbbell', false, null),
(gen_random_uuid(), 'Dumbbell Front Raise', 'dumbbell', 'shoulders', ARRAY['chest'], 'dumbbell', false, null),
(gen_random_uuid(), 'Dumbbell Skullcrusher', 'dumbbell', 'triceps', ARRAY['chest'], 'dumbbell', false, null),
(gen_random_uuid(), 'Dumbbell Calf Raise', 'dumbbell', 'calves', ARRAY[]::text[], 'dumbbell', false, null),
(gen_random_uuid(), 'Dumbbell Arnold Press', 'dumbbell', 'shoulders', ARRAY['triceps','chest'], 'dumbbell', false, null),
(gen_random_uuid(), 'Dumbbell Shrug', 'dumbbell', 'back', ARRAY['shoulders'], 'dumbbell', false, null),

-- MACHINE (20)
(gen_random_uuid(), 'Lat Pulldown', 'machine', 'back', ARRAY['biceps'], 'machine', false, null),
(gen_random_uuid(), 'Cable Row', 'machine', 'back', ARRAY['biceps','core'], 'cable', false, null),
(gen_random_uuid(), 'Leg Press', 'machine', 'quadriceps', ARRAY['glutes','hamstrings'], 'machine', false, null),
(gen_random_uuid(), 'Leg Curl', 'machine', 'hamstrings', ARRAY['calves'], 'machine', false, null),
(gen_random_uuid(), 'Leg Extension', 'machine', 'quadriceps', ARRAY[]::text[], 'machine', false, null),
(gen_random_uuid(), 'Chest Press Machine', 'machine', 'chest', ARRAY['shoulders','triceps'], 'machine', false, null),
(gen_random_uuid(), 'Pec Deck Fly', 'machine', 'chest', ARRAY['shoulders'], 'machine', false, null),
(gen_random_uuid(), 'Seated Row Machine', 'machine', 'back', ARRAY['biceps'], 'machine', false, null),
(gen_random_uuid(), 'Shoulder Press Machine', 'machine', 'shoulders', ARRAY['triceps'], 'machine', false, null),
(gen_random_uuid(), 'Cable Bicep Curl', 'machine', 'biceps', ARRAY['forearms'], 'cable', false, null),
(gen_random_uuid(), 'Cable Tricep Pushdown', 'machine', 'triceps', ARRAY['forearms'], 'cable', false, null),
(gen_random_uuid(), 'Cable Lateral Raise', 'machine', 'shoulders', ARRAY[]::text[], 'cable', false, null),
(gen_random_uuid(), 'Cable Face Pull', 'machine', 'shoulders', ARRAY['back'], 'cable', false, null),
(gen_random_uuid(), 'Hip Abduction Machine', 'machine', 'glutes', ARRAY[]::text[], 'machine', false, null),
(gen_random_uuid(), 'Hip Adduction Machine', 'machine', 'glutes', ARRAY['quadriceps'], 'machine', false, null),
(gen_random_uuid(), 'Smith Machine Squat', 'machine', 'quadriceps', ARRAY['glutes','hamstrings'], 'machine', false, null),
(gen_random_uuid(), 'Assisted Pull-Up Machine', 'machine', 'back', ARRAY['biceps'], 'machine', false, null),
(gen_random_uuid(), 'Hack Squat', 'machine', 'quadriceps', ARRAY['glutes'], 'machine', false, null),
(gen_random_uuid(), 'Glute Kickback Machine', 'machine', 'glutes', ARRAY['hamstrings'], 'machine', false, null),
(gen_random_uuid(), 'Cable Woodchop', 'machine', 'core', ARRAY['shoulders','back'], 'cable', false, null),

-- BODYWEIGHT (20)
(gen_random_uuid(), 'Pull-Up', 'bodyweight', 'back', ARRAY['biceps','core'], 'bodyweight', false, null),
(gen_random_uuid(), 'Push-Up', 'bodyweight', 'chest', ARRAY['shoulders','triceps'], 'bodyweight', false, null),
(gen_random_uuid(), 'Dip', 'bodyweight', 'triceps', ARRAY['chest','shoulders'], 'bodyweight', false, null),
(gen_random_uuid(), 'Plank', 'bodyweight', 'core', ARRAY['shoulders','back'], 'bodyweight', false, null),
(gen_random_uuid(), 'Hollow Body Hold', 'bodyweight', 'core', ARRAY['back'], 'bodyweight', false, null),
(gen_random_uuid(), 'Pistol Squat', 'bodyweight', 'quadriceps', ARRAY['glutes','core'], 'bodyweight', false, null),
(gen_random_uuid(), 'Chin-Up', 'bodyweight', 'back', ARRAY['biceps'], 'bodyweight', false, null),
(gen_random_uuid(), 'Inverted Row', 'bodyweight', 'back', ARRAY['biceps','core'], 'bodyweight', false, null),
(gen_random_uuid(), 'Bodyweight Squat', 'bodyweight', 'quadriceps', ARRAY['glutes'], 'bodyweight', false, null),
(gen_random_uuid(), 'Bodyweight Lunge', 'bodyweight', 'quadriceps', ARRAY['glutes','hamstrings'], 'bodyweight', false, null),
(gen_random_uuid(), 'Glute Bridge', 'bodyweight', 'glutes', ARRAY['hamstrings','core'], 'bodyweight', false, null),
(gen_random_uuid(), 'Side Plank', 'bodyweight', 'core', ARRAY['shoulders'], 'bodyweight', false, null),
(gen_random_uuid(), 'Hanging Leg Raise', 'bodyweight', 'core', ARRAY['hip_flexors'], 'bodyweight', false, null),
(gen_random_uuid(), 'Handstand Push-Up', 'bodyweight', 'shoulders', ARRAY['triceps','core'], 'bodyweight', false, null),
(gen_random_uuid(), 'Muscle-Up', 'bodyweight', 'back', ARRAY['chest','triceps','biceps'], 'bodyweight', false, null),
(gen_random_uuid(), 'Nordic Hamstring Curl', 'bodyweight', 'hamstrings', ARRAY['glutes'], 'bodyweight', false, null),
(gen_random_uuid(), 'Box Jump', 'bodyweight', 'quadriceps', ARRAY['glutes','calves'], 'bodyweight', false, null),
(gen_random_uuid(), 'Burpee', 'bodyweight', 'full_body', ARRAY['core','chest','shoulders'], 'bodyweight', false, null),
(gen_random_uuid(), 'Mountain Climber', 'bodyweight', 'core', ARRAY['shoulders','quadriceps'], 'bodyweight', false, null),
(gen_random_uuid(), 'Superman Hold', 'bodyweight', 'back', ARRAY['glutes','core'], 'bodyweight', false, null),

-- CARDIO (10)
(gen_random_uuid(), 'Running', 'cardio', 'cardio', ARRAY['quadriceps','calves','glutes'], 'cardio_machine', false, null),
(gen_random_uuid(), 'Cycling', 'cardio', 'cardio', ARRAY['quadriceps','hamstrings','calves'], 'cardio_machine', false, null),
(gen_random_uuid(), 'Rowing Machine', 'cardio', 'cardio', ARRAY['back','core','quadriceps'], 'cardio_machine', false, null),
(gen_random_uuid(), 'Swimming', 'cardio', 'cardio', ARRAY['back','shoulders','chest','core'], 'none', false, null),
(gen_random_uuid(), 'Jump Rope', 'cardio', 'cardio', ARRAY['calves','shoulders','core'], 'none', false, null),
(gen_random_uuid(), 'Elliptical', 'cardio', 'cardio', ARRAY['quadriceps','glutes','hamstrings'], 'cardio_machine', false, null),
(gen_random_uuid(), 'Stair Climber', 'cardio', 'cardio', ARRAY['glutes','quadriceps','calves'], 'cardio_machine', false, null),
(gen_random_uuid(), 'Battle Ropes', 'cardio', 'cardio', ARRAY['shoulders','core','back'], 'none', false, null),
(gen_random_uuid(), 'Assault Bike', 'cardio', 'cardio', ARRAY['full_body'], 'cardio_machine', false, null),
(gen_random_uuid(), 'Sled Push', 'cardio', 'quadriceps', ARRAY['glutes','core','shoulders'], 'none', false, null),

-- MOBILITY (10)
(gen_random_uuid(), 'Hip Flexor Stretch', 'mobility', 'flexibility', ARRAY['quadriceps'], 'none', false, null),
(gen_random_uuid(), 'Pigeon Pose', 'mobility', 'flexibility', ARRAY['glutes','hip_flexors'], 'none', false, null),
(gen_random_uuid(), '90/90 Hip Rotation', 'mobility', 'flexibility', ARRAY['glutes','hip_flexors'], 'none', false, null),
(gen_random_uuid(), 'Cat-Cow Stretch', 'mobility', 'flexibility', ARRAY['core','back'], 'none', false, null),
(gen_random_uuid(), 'Thoracic Spine Rotation', 'mobility', 'flexibility', ARRAY['back','shoulders'], 'none', false, null),
(gen_random_uuid(), 'World''s Greatest Stretch', 'mobility', 'full_body', ARRAY['flexibility'], 'none', false, null),
(gen_random_uuid(), 'Cossack Squat', 'mobility', 'flexibility', ARRAY['quadriceps','glutes','hamstrings'], 'none', false, null),
(gen_random_uuid(), 'Couch Stretch', 'mobility', 'flexibility', ARRAY['quadriceps','hip_flexors'], 'none', false, null),
(gen_random_uuid(), 'Dead Hang', 'mobility', 'back', ARRAY['shoulders','core'], 'bodyweight', false, null),
(gen_random_uuid(), 'Ankle Circles', 'mobility', 'flexibility', ARRAY['calves'], 'none', false, null);
