-- Curated exercise library: adds the default exercise set used by the
-- exercise picker. Non-destructive — only inserts exercises whose name
-- doesn't already exist, so it's safe to re-run and won't touch any
-- user-created exercises, templates, or logged session history.

alter table public.exercises
  add column if not exists logging_type text default 'weight_reps';

insert into exercises (name, category, muscle_primary, muscle_secondary, equipment, is_custom, user_id, logging_type)
select v.name, v.category, v.muscle_primary, v.muscle_secondary::text[], v.equipment, false, null, v.logging_type
from (values

-- BACK
('Barbell Stiff Leg Deadlift','back','lower back',ARRAY['hamstrings','glutes'],'barbell','weight_reps'),
('Behind the Back Shrug','back','traps',ARRAY['upper back'],'barbell','weight_reps'),
('Behind the Back Shrug (Smith Machine)','back','traps',ARRAY['upper back'],'machine','weight_reps'),
('Behind the Neck Lat Pull Down','back','lats',ARRAY['biceps','upper back'],'cable','weight_reps'),
('Bent Over Row','back','upper back',ARRAY['lats','biceps','rear delts'],'barbell','weight_reps'),
('Bent Over Row (Cable)','back','upper back',ARRAY['lats','biceps'],'cable','weight_reps'),
('Bent Over Row (Dumbbell)','back','upper back',ARRAY['lats','biceps'],'dumbbell','weight_reps'),
('Bent Over Row (Smith Machine)','back','upper back',ARRAY['lats','biceps'],'machine','weight_reps'),
('Bent Over Row (T-Bar)','back','upper back',ARRAY['lats','biceps'],'other','weight_reps'),
('Bird Dog','back','lower back',ARRAY['core','glutes'],'bodyweight','time_reps'),
('Cable Pullover','back','lats',ARRAY['chest','triceps'],'cable','weight_reps'),
('Hyperextension','back','lower back',ARRAY['glutes','hamstrings'],'bodyweight','weight_reps'),
('Hyperextension (Stability Ball)','back','lower back',ARRAY['glutes','hamstrings'],'other','weight_reps'),
('Incline Row (Barbell)','back','upper back',ARRAY['lats','biceps'],'barbell','weight_reps'),
('Incline Row (Cable)','back','upper back',ARRAY['lats','biceps'],'cable','weight_reps'),
('Incline Row (Dumbbell)','back','upper back',ARRAY['lats','biceps'],'dumbbell','weight_reps'),
('Incline Shrug (Dumbbell)','back','traps',ARRAY['upper back'],'dumbbell','weight_reps'),
('Inverted Row','back','upper back',ARRAY['lats','biceps'],'bodyweight','weight_reps'),
('Lat Pull Down (Close Grip)','back','lats',ARRAY['biceps','upper back'],'cable','weight_reps'),
('Lat Pull Down (Cable)','back','lats',ARRAY['biceps','upper back'],'cable','weight_reps'),
('Lat Pull Down (Machine)','back','lats',ARRAY['biceps','upper back'],'machine','weight_reps'),
('Pendlay Row','back','upper back',ARRAY['lats','biceps'],'barbell','weight_reps'),
('Pull Up','back','lats',ARRAY['biceps','upper back'],'bodyweight','weight_reps'),
('Pull Up (Close Grip)','back','lats',ARRAY['biceps','upper back'],'bodyweight','weight_reps'),
('Pull Up (Wide Grip)','back','lats',ARRAY['biceps','upper back'],'bodyweight','weight_reps'),
('Reverse Hyperextension','back','lower back',ARRAY['glutes','hamstrings'],'bodyweight','weight_reps'),
('Reverse Hyperextension (Machine)','back','lower back',ARRAY['glutes','hamstrings'],'machine','weight_reps'),
('Seated Row (Cable)','back','upper back',ARRAY['lats','biceps'],'cable','weight_reps'),
('Seated Row (Machine)','back','upper back',ARRAY['lats','biceps'],'machine','weight_reps'),
('Shrug (Barbell)','back','traps',ARRAY['upper back'],'barbell','weight_reps'),
('Shrug (Cable)','back','traps',ARRAY['upper back'],'cable','weight_reps'),
('Shrug (Dumbbell)','back','traps',ARRAY['upper back'],'dumbbell','weight_reps'),
('Shrug (Machine)','back','traps',ARRAY['upper back'],'machine','weight_reps'),
('Shrug (Smith Machine)','back','traps',ARRAY['upper back'],'machine','weight_reps'),
('Single Arm Bent Over Row (Cable)','back','upper back',ARRAY['lats','biceps'],'cable','weight_reps'),
('Single Arm Bent Over Row (Dumbbell)','back','upper back',ARRAY['lats','biceps'],'dumbbell','weight_reps'),
('Single Arm Cable Row (Decline)','back','upper back',ARRAY['lats','biceps'],'cable','weight_reps'),
('Single Arm Cable Row (Standing)','back','upper back',ARRAY['lats','biceps'],'cable','weight_reps'),
('Single Arm Lat Pull Down (Machine)','back','lats',ARRAY['biceps'],'machine','weight_reps'),
('Single Arm Row (Machine)','back','upper back',ARRAY['lats','biceps'],'machine','weight_reps'),
('Standing Row (Cable)','back','upper back',ARRAY['lats','biceps'],'cable','weight_reps'),
('Straight Arm Lat Pull Down','back','lats',ARRAY['triceps','core'],'cable','weight_reps'),
('Superman','back','lower back',ARRAY['glutes','hamstrings'],'bodyweight','time_reps'),

-- CHEST
('Barbell Pin Bench Press','chest','chest',ARRAY['triceps','shoulders'],'barbell','weight_reps'),
('Bench Press','chest','chest',ARRAY['triceps','shoulders'],'barbell','weight_reps'),
('Bench Press (Cable)','chest','chest',ARRAY['triceps','shoulders'],'cable','weight_reps'),
('Bench Press (Dumbbell)','chest','chest',ARRAY['triceps','shoulders'],'dumbbell','weight_reps'),
('Bench Press (Smith Machine)','chest','chest',ARRAY['triceps','shoulders'],'machine','weight_reps'),
('Cable Crossover (Down to Up)','chest','chest',ARRAY['shoulders'],'cable','weight_reps'),
('Chest Dip','chest','chest',ARRAY['triceps','shoulders'],'bodyweight','weight_reps'),
('Chest Fly (Cable)','chest','chest',ARRAY['shoulders'],'cable','weight_reps'),
('Chest Fly (Dumbbell)','chest','chest',ARRAY['shoulders'],'dumbbell','weight_reps'),
('Chest Fly (Machine)','chest','chest',ARRAY['shoulders'],'machine','weight_reps'),
('Decline Bench Press (Barbell)','chest','chest',ARRAY['triceps'],'barbell','weight_reps'),
('Decline Bench Press (Cable)','chest','chest',ARRAY['triceps'],'cable','weight_reps'),
('Decline Bench Press (Dumbbell)','chest','chest',ARRAY['triceps'],'dumbbell','weight_reps'),
('Decline Bench Press (Smith Machine)','chest','chest',ARRAY['triceps'],'machine','weight_reps'),
('Decline Chest Fly (Cable)','chest','chest',ARRAY['shoulders'],'cable','weight_reps'),
('Decline Chest Fly (Dumbbell)','chest','chest',ARRAY['shoulders'],'dumbbell','weight_reps'),
('Decline Push Up','chest','chest',ARRAY['triceps','shoulders'],'bodyweight','weight_reps'),
('Hammer Strength Press (Machine)','chest','chest',ARRAY['triceps','shoulders'],'machine','weight_reps'),
('Incline Bench Press (Barbell)','chest','chest',ARRAY['triceps','front delts'],'barbell','weight_reps'),
('Incline Bench Press (Cable)','chest','chest',ARRAY['triceps','front delts'],'cable','weight_reps'),
('Incline Bench Press (Dumbbell)','chest','chest',ARRAY['triceps','front delts'],'dumbbell','weight_reps'),
('Incline Bench Press (Smith Machine)','chest','chest',ARRAY['triceps','front delts'],'machine','weight_reps'),
('Incline Chest Fly (Cable)','chest','chest',ARRAY['front delts'],'cable','weight_reps'),
('Incline Chest Fly (Dumbbell)','chest','chest',ARRAY['front delts'],'dumbbell','weight_reps'),
('Incline Push Up','chest','chest',ARRAY['triceps','shoulders'],'bodyweight','weight_reps'),
('Lying Around the World (Dumbbell)','chest','chest',ARRAY['shoulders'],'dumbbell','weight_reps'),
('Pec Deck (Machine)','chest','chest',ARRAY['shoulders'],'machine','weight_reps'),
('Pullover (Barbell)','chest','chest',ARRAY['lats','triceps'],'barbell','weight_reps'),
('Pullover (Cable)','chest','chest',ARRAY['lats','triceps'],'cable','weight_reps'),
('Pullover (Dumbbell)','chest','chest',ARRAY['lats','triceps'],'dumbbell','weight_reps'),
('Pullover (Machine)','chest','chest',ARRAY['lats','triceps'],'machine','weight_reps'),
('Push Up','chest','chest',ARRAY['triceps','shoulders'],'bodyweight','weight_reps'),
('Standing Chest Fly (Cable)','chest','chest',ARRAY['shoulders'],'cable','weight_reps'),
('Standing Chest Press (Cable)','chest','chest',ARRAY['triceps','shoulders'],'cable','weight_reps'),

-- SHOULDERS
('Arnold Press (Dumbbell)','shoulders','shoulders',ARRAY['front delts','side delts','triceps'],'dumbbell','weight_reps'),
('Behind the Neck Overhead Press (Smith Machine)','shoulders','shoulders',ARRAY['triceps','traps'],'machine','weight_reps'),
('Behind the Neck Press (Barbell)','shoulders','shoulders',ARRAY['triceps','traps'],'barbell','weight_reps'),
('Bent Over Rear Delt Row (Barbell)','shoulders','rear delts',ARRAY['upper back','biceps'],'barbell','weight_reps'),
('Bent Over Rear Delt Row (Dumbbell)','shoulders','rear delts',ARRAY['upper back','biceps'],'dumbbell','weight_reps'),
('Bent Over Rear Delt Row (Smith Machine)','shoulders','rear delts',ARRAY['upper back','biceps'],'machine','weight_reps'),
('Bent Over Reverse Fly (Cable)','shoulders','rear delts',ARRAY['upper back'],'cable','weight_reps'),
('Bent Over Reverse Fly (Dumbbell)','shoulders','rear delts',ARRAY['upper back'],'dumbbell','weight_reps'),
('Cuban Press (Dumbbell)','shoulders','shoulders',ARRAY['rear delts','rotator cuff'],'dumbbell','weight_reps'),
('External Rotation (Cable)','shoulders','rotator cuff',ARRAY['rear delts'],'cable','weight_reps'),
('Front Raise (Barbell)','shoulders','front delts',ARRAY['side delts'],'barbell','weight_reps'),
('Front Raise (Cable)','shoulders','front delts',ARRAY['side delts'],'cable','weight_reps'),
('Front Raise (Dumbbell)','shoulders','front delts',ARRAY['side delts'],'dumbbell','weight_reps'),
('Front Raise (Plate)','shoulders','front delts',ARRAY['side delts'],'other','weight_reps'),
('Handstand Push Up','shoulders','shoulders',ARRAY['triceps','traps'],'bodyweight','weight_reps'),
('Incline Around the World (Dumbbell)','shoulders','front delts',ARRAY['side delts'],'dumbbell','weight_reps'),
('Internal Rotation (Cable)','shoulders','rotator cuff',ARRAY['front delts'],'cable','weight_reps'),
('Lateral Raise (Cable)','shoulders','side delts',ARRAY['traps'],'cable','weight_reps'),
('Lateral Raise (Dumbbell)','shoulders','side delts',ARRAY['traps'],'dumbbell','weight_reps'),
('Lateral Raise (Machine)','shoulders','side delts',ARRAY['traps'],'machine','weight_reps'),
('Lying Reverse Fly (Dumbbell)','shoulders','rear delts',ARRAY['upper back'],'dumbbell','weight_reps'),
('Overhead Press (Barbell)','shoulders','shoulders',ARRAY['triceps','front delts','traps'],'barbell','weight_reps'),
('Overhead Press (Cable)','shoulders','shoulders',ARRAY['triceps','front delts'],'cable','weight_reps'),
('Overhead Press (Dumbbell)','shoulders','shoulders',ARRAY['triceps','front delts'],'dumbbell','weight_reps'),
('Overhead Press (Machine)','shoulders','shoulders',ARRAY['triceps','front delts'],'machine','weight_reps'),
('Overhead Press (Smith Machine)','shoulders','shoulders',ARRAY['triceps','front delts'],'machine','weight_reps'),
('Pike Push Up','shoulders','shoulders',ARRAY['triceps'],'bodyweight','weight_reps'),
('Plate Lateral Raise','shoulders','side delts',ARRAY['traps'],'other','weight_reps'),
('Push Press (Barbell)','shoulders','shoulders',ARRAY['triceps','quads'],'barbell','weight_reps'),
('Rear Delt Row (Cable)','shoulders','rear delts',ARRAY['upper back','biceps'],'cable','weight_reps'),
('Reverse Fly (Cable)','shoulders','rear delts',ARRAY['upper back'],'cable','weight_reps'),
('Reverse Fly (Machine)','shoulders','rear delts',ARRAY['upper back'],'machine','weight_reps'),
('Seated Overhead Press (Barbell)','shoulders','shoulders',ARRAY['triceps','front delts'],'barbell','weight_reps'),
('Seated Overhead Press (Dumbbell)','shoulders','shoulders',ARRAY['triceps','front delts'],'dumbbell','weight_reps'),
('Single Arm Cable Lateral Raise','shoulders','side delts',ARRAY['traps'],'cable','weight_reps'),
('Single Arm Dumbbell Lateral Raise','shoulders','side delts',ARRAY['traps'],'dumbbell','weight_reps'),
('Single Arm Jerk','shoulders','shoulders',ARRAY['triceps','quads'],'other','weight_reps'),
('Single Arm Kettlebell Press','shoulders','shoulders',ARRAY['triceps','core'],'kettlebell','weight_reps'),
('Standing Around the World (Dumbbell)','shoulders','shoulders',ARRAY['side delts','front delts'],'dumbbell','weight_reps'),
('Upright Row (Barbell)','shoulders','side delts',ARRAY['traps','biceps'],'barbell','weight_reps'),
('Upright Row (Cable)','shoulders','side delts',ARRAY['traps','biceps'],'cable','weight_reps'),
('Upright Row (Dumbbell)','shoulders','side delts',ARRAY['traps','biceps'],'dumbbell','weight_reps'),
('Upright Row (Smith Machine)','shoulders','side delts',ARRAY['traps','biceps'],'machine','weight_reps'),

-- ARMS - BICEPS
('Chin Up','arms','biceps',ARRAY['lats','upper back'],'bodyweight','weight_reps'),
('Chin Up (Close Grip)','arms','biceps',ARRAY['lats'],'bodyweight','weight_reps'),
('Chin Up (Wide Grip)','arms','biceps',ARRAY['lats'],'bodyweight','weight_reps'),
('Concentration Curl (Barbell)','arms','biceps',ARRAY['forearms'],'barbell','weight_reps'),
('Concentration Curl (Cable)','arms','biceps',ARRAY['forearms'],'cable','weight_reps'),
('Concentration Curl (Dumbbell)','arms','biceps',ARRAY['forearms'],'dumbbell','weight_reps'),
('Curl (Barbell)','arms','biceps',ARRAY['forearms'],'barbell','weight_reps'),
('Curl (Cable)','arms','biceps',ARRAY['forearms'],'cable','weight_reps'),
('Curl (Dumbbell)','arms','biceps',ARRAY['forearms'],'dumbbell','weight_reps'),
('Curl (Machine)','arms','biceps',ARRAY['forearms'],'machine','weight_reps'),
('Hammer Curl (Cable)','arms','biceps',ARRAY['forearms','brachialis'],'cable','weight_reps'),
('Hammer Curl (Dumbbell)','arms','biceps',ARRAY['forearms','brachialis'],'dumbbell','weight_reps'),
('Incline Curl (Dumbbell)','arms','biceps',ARRAY['forearms'],'dumbbell','weight_reps'),
('Lat Pull Down (Reverse Grip)','arms','biceps',ARRAY['lats','upper back'],'cable','weight_reps'),
('Pinwheel Curl (Dumbbell)','arms','biceps',ARRAY['forearms','brachialis'],'dumbbell','weight_reps'),
('Preacher Curl (Barbell)','arms','biceps',ARRAY['forearms'],'barbell','weight_reps'),
('Preacher Curl (Cable)','arms','biceps',ARRAY['forearms'],'cable','weight_reps'),
('Preacher Curl (Dumbbell)','arms','biceps',ARRAY['forearms'],'dumbbell','weight_reps'),
('Preacher Hammer Curl (Dumbbell)','arms','biceps',ARRAY['forearms','brachialis'],'dumbbell','weight_reps'),
('Reverse Concentration Curl (Dumbbell)','arms','forearms',ARRAY['biceps'],'dumbbell','weight_reps'),
('Reverse Curl (Barbell)','arms','forearms',ARRAY['biceps'],'barbell','weight_reps'),
('Reverse Curl (Cable)','arms','forearms',ARRAY['biceps'],'cable','weight_reps'),
('Reverse Curl (Dumbbell)','arms','forearms',ARRAY['biceps'],'dumbbell','weight_reps'),
('Single Arm Cable Curl','arms','biceps',ARRAY['forearms'],'cable','weight_reps'),
('Single Arm Preacher Curl (Dumbbell)','arms','biceps',ARRAY['forearms'],'dumbbell','weight_reps'),
('Spider Curl (Barbell)','arms','biceps',ARRAY['forearms'],'barbell','weight_reps'),
('Spider Curl (Dumbbell)','arms','biceps',ARRAY['forearms'],'dumbbell','weight_reps'),
('Supinating Curl (Dumbbell)','arms','biceps',ARRAY['forearms'],'dumbbell','weight_reps'),
('Zottman Curl (Dumbbell)','arms','biceps',ARRAY['forearms','brachialis'],'dumbbell','weight_reps'),

-- ARMS - TRICEPS
('Bench Press (Close Grip)','arms','triceps',ARRAY['chest','front delts'],'barbell','weight_reps'),
('Bench Press (Close Grip Dumbbell)','arms','triceps',ARRAY['chest','front delts'],'dumbbell','weight_reps'),
('Bench Press (Close Grip Smith Machine)','arms','triceps',ARRAY['chest','front delts'],'machine','weight_reps'),
('Bodyweight Tricep Extension','arms','triceps',ARRAY['chest'],'bodyweight','weight_reps'),
('Diamond Push Up','arms','triceps',ARRAY['chest','shoulders'],'bodyweight','weight_reps'),
('Kneeling Overhead Tricep Extension (Dumbbell)','arms','triceps',ARRAY[]::text[],'dumbbell','weight_reps'),
('Lying Tricep Extension (Barbell)','arms','triceps',ARRAY['forearms'],'barbell','weight_reps'),
('Lying Tricep Extension (Cable)','arms','triceps',ARRAY['forearms'],'cable','weight_reps'),
('Lying Tricep Extension (Dumbbell)','arms','triceps',ARRAY['forearms'],'dumbbell','weight_reps'),
('Overhead Tricep Extension (Cable)','arms','triceps',ARRAY[]::text[],'cable','weight_reps'),
('Seated Overhead Tricep Extension (Barbell)','arms','triceps',ARRAY[]::text[],'barbell','weight_reps'),
('Seated Overhead Tricep Extension (Dumbbell)','arms','triceps',ARRAY[]::text[],'dumbbell','weight_reps'),
('Side Push Up','arms','triceps',ARRAY['chest'],'bodyweight','weight_reps'),
('Single Arm Cable Tricep Extension','arms','triceps',ARRAY[]::text[],'cable','weight_reps'),
('Single Arm Overhead Tricep Extension (Dumbbell)','arms','triceps',ARRAY[]::text[],'dumbbell','weight_reps'),
('Single Arm Tricep Kickback','arms','triceps',ARRAY[]::text[],'dumbbell','weight_reps'),
('Tricep Dip','arms','triceps',ARRAY['chest','shoulders'],'bodyweight','weight_reps'),
('Tricep Dip (Bench)','arms','triceps',ARRAY['chest','shoulders'],'bodyweight','weight_reps'),
('Tricep Dip (Machine)','arms','triceps',ARRAY['chest','shoulders'],'machine','weight_reps'),
('Tricep Extension (Cable)','arms','triceps',ARRAY[]::text[],'cable','weight_reps'),
('Tricep Extension (Machine)','arms','triceps',ARRAY[]::text[],'machine','weight_reps'),
('Tricep Kickback (Cable)','arms','triceps',ARRAY[]::text[],'cable','weight_reps'),
('Tricep Kickback (Dumbbell)','arms','triceps',ARRAY[]::text[],'dumbbell','weight_reps'),

-- ARMS - FOREARMS / WRISTS
('Behind the Back Wrist Curl (Barbell)','arms','forearms',ARRAY[]::text[],'barbell','weight_reps'),
('Wrist Curl (Barbell)','arms','forearms',ARRAY[]::text[],'barbell','weight_reps'),
('Wrist Curl (Cable)','arms','forearms',ARRAY[]::text[],'cable','weight_reps'),
('Wrist Curl (Dumbbell)','arms','forearms',ARRAY[]::text[],'dumbbell','weight_reps'),
('Wrist Extension (Dumbbell)','arms','forearms',ARRAY[]::text[],'dumbbell','weight_reps'),

-- LEGS
('Bench Squat (Barbell)','legs','quads',ARRAY['glutes','hamstrings'],'barbell','weight_reps'),
('Bench Squat (Dumbbell)','legs','quads',ARRAY['glutes','hamstrings'],'dumbbell','weight_reps'),
('Box Jump','legs','quads',ARRAY['glutes','calves'],'bodyweight','weight_reps'),
('Bulgarian Split Squat','legs','quads',ARRAY['glutes','hamstrings'],'bodyweight','weight_reps'),
('Bulgarian Split Squat (Barbell)','legs','quads',ARRAY['glutes','hamstrings'],'barbell','weight_reps'),
('Bulgarian Split Squat (Dumbbell)','legs','quads',ARRAY['glutes','hamstrings'],'dumbbell','weight_reps'),
('Calf Press (Machine)','legs','calves',ARRAY[]::text[],'machine','weight_reps'),
('Carioca Lunge','legs','quads',ARRAY['glutes','hamstrings'],'bodyweight','weight_reps'),
('Carioca Lunge (Dumbbell)','legs','quads',ARRAY['glutes','hamstrings'],'dumbbell','weight_reps'),
('Deadlift (Barbell)','legs','hamstrings',ARRAY['glutes','lower back','quads','traps'],'barbell','weight_reps'),
('Deadlift (Dumbbell)','legs','hamstrings',ARRAY['glutes','lower back'],'dumbbell','weight_reps'),
('Deadlift (Smith Machine)','legs','hamstrings',ARRAY['glutes','lower back'],'machine','weight_reps'),
('Fire Hydrant','legs','glutes',ARRAY['abductors'],'bodyweight','weight_reps'),
('Front Squat (Barbell)','legs','quads',ARRAY['glutes','core'],'barbell','weight_reps'),
('Front Squat (Cable)','legs','quads',ARRAY['glutes','core'],'cable','weight_reps'),
('Front Squat (Dumbbell)','legs','quads',ARRAY['glutes','core'],'dumbbell','weight_reps'),
('Front Squat (Smith Machine)','legs','quads',ARRAY['glutes','core'],'machine','weight_reps'),
('Glute Bridge','legs','glutes',ARRAY['hamstrings','core'],'bodyweight','weight_reps'),
('Glute Bridge (Barbell)','legs','glutes',ARRAY['hamstrings','core'],'barbell','weight_reps'),
('Glute Bridge (Dumbbell)','legs','glutes',ARRAY['hamstrings','core'],'dumbbell','weight_reps'),
('Glute Ham Raise','legs','hamstrings',ARRAY['glutes','lower back'],'bodyweight','weight_reps'),
('Glute Kickback','legs','glutes',ARRAY['hamstrings'],'bodyweight','weight_reps'),
('Glute Kickback (Cable)','legs','glutes',ARRAY['hamstrings'],'cable','weight_reps'),
('Glute Kickback (Machine)','legs','glutes',ARRAY['hamstrings'],'machine','weight_reps'),
('Good Morning (Barbell)','legs','hamstrings',ARRAY['glutes','lower back'],'barbell','weight_reps'),
('Good Morning (Smith Machine)','legs','hamstrings',ARRAY['glutes','lower back'],'machine','weight_reps'),
('Hack Squat (Barbell)','legs','quads',ARRAY['glutes','hamstrings'],'barbell','weight_reps'),
('Hack Squat (Machine)','legs','quads',ARRAY['glutes','hamstrings'],'machine','weight_reps'),
('Hack Squat (Smith Machine)','legs','quads',ARRAY['glutes','hamstrings'],'machine','weight_reps'),
('Hip Abduction (Cable)','legs','abductors',ARRAY['glutes'],'cable','weight_reps'),
('Hip Abduction (Machine)','legs','abductors',ARRAY['glutes'],'machine','weight_reps'),
('Hip Adduction (Machine)','legs','adductors',ARRAY[]::text[],'machine','weight_reps'),
('Hip Flexion (Cable)','legs','hip flexors',ARRAY['quads'],'cable','weight_reps'),
('Hip Flexion (Machine)','legs','hip flexors',ARRAY['quads'],'machine','weight_reps'),
('Hip Thrust (Barbell)','legs','glutes',ARRAY['hamstrings','core'],'barbell','weight_reps'),
('Hip Thrust (Smith Machine)','legs','glutes',ARRAY['hamstrings','core'],'machine','weight_reps'),
('Lateral Step Up','legs','quads',ARRAY['glutes','abductors'],'bodyweight','weight_reps'),
('Leg Curl (Machine)','legs','hamstrings',ARRAY['glutes'],'machine','weight_reps'),
('Leg Extension (Machine)','legs','quads',ARRAY[]::text[],'machine','weight_reps'),
('Leg Press (Calf)','legs','calves',ARRAY[]::text[],'machine','weight_reps'),
('Leg Press (Machine)','legs','quads',ARRAY['glutes','hamstrings'],'machine','weight_reps'),
('Lunge (Barbell)','legs','quads',ARRAY['glutes','hamstrings'],'barbell','weight_reps'),
('Lunge (Dumbbell)','legs','quads',ARRAY['glutes','hamstrings'],'dumbbell','weight_reps'),
('Lunge (Smith Machine)','legs','quads',ARRAY['glutes','hamstrings'],'machine','weight_reps'),
('Lying Leg Curl (Machine)','legs','hamstrings',ARRAY['glutes'],'machine','weight_reps'),
('Overhead Squat','legs','quads',ARRAY['glutes','shoulders','core'],'barbell','weight_reps'),
('Rack Pull (Barbell)','legs','hamstrings',ARRAY['lower back','glutes','traps'],'barbell','weight_reps'),
('Reverse Lunge','legs','quads',ARRAY['glutes','hamstrings'],'bodyweight','weight_reps'),
('Reverse Lunge (Dumbbell)','legs','quads',ARRAY['glutes','hamstrings'],'dumbbell','weight_reps'),
('Reverse Lunge (Smith Machine)','legs','quads',ARRAY['glutes','hamstrings'],'machine','weight_reps'),
('Romanian Deadlift (Barbell)','legs','hamstrings',ARRAY['glutes','lower back'],'barbell','weight_reps'),
('Romanian Deadlift (Dumbbell)','legs','hamstrings',ARRAY['glutes','lower back'],'dumbbell','weight_reps'),
('Seated Calf Raise (Barbell)','legs','calves',ARRAY[]::text[],'barbell','weight_reps'),
('Seated Calf Raise (Dumbbell)','legs','calves',ARRAY[]::text[],'dumbbell','weight_reps'),
('Seated Calf Raise (Machine)','legs','calves',ARRAY[]::text[],'machine','weight_reps'),
('Side Lunge','legs','adductors',ARRAY['quads','glutes'],'bodyweight','weight_reps'),
('Side Lunge (Barbell)','legs','adductors',ARRAY['quads','glutes'],'barbell','weight_reps'),
('Side Lunge (Dumbbell)','legs','adductors',ARRAY['quads','glutes'],'dumbbell','weight_reps'),
('Side Lying Hip Abduction','legs','abductors',ARRAY['glutes'],'bodyweight','weight_reps'),
('Side Lying Hip Adduction (Dumbbell)','legs','adductors',ARRAY[]::text[],'dumbbell','weight_reps'),
('Single Leg Glute Bridge','legs','glutes',ARRAY['hamstrings','core'],'bodyweight','weight_reps'),
('Single Leg Squat','legs','quads',ARRAY['glutes','hamstrings','core'],'bodyweight','weight_reps'),
('Split Squat','legs','quads',ARRAY['glutes','hamstrings'],'bodyweight','weight_reps'),
('Split Squat (Barbell)','legs','quads',ARRAY['glutes','hamstrings'],'barbell','weight_reps'),
('Split Squat (Dumbbell)','legs','quads',ARRAY['glutes','hamstrings'],'dumbbell','weight_reps'),
('Split Squat (Smith Machine)','legs','quads',ARRAY['glutes','hamstrings'],'machine','weight_reps'),
('Squat','legs','quads',ARRAY['glutes','hamstrings','core'],'bodyweight','weight_reps'),
('Squat (Barbell)','legs','quads',ARRAY['glutes','hamstrings','core'],'barbell','weight_reps'),
('Squat (Dumbbell)','legs','quads',ARRAY['glutes','hamstrings'],'dumbbell','weight_reps'),
('Squat (Smith Machine)','legs','quads',ARRAY['glutes','hamstrings'],'machine','weight_reps'),
('Standing Calf Raise (Barbell)','legs','calves',ARRAY[]::text[],'barbell','weight_reps'),
('Standing Calf Raise (Dumbbell)','legs','calves',ARRAY[]::text[],'dumbbell','weight_reps'),
('Standing Calf Raise (Machine)','legs','calves',ARRAY[]::text[],'machine','weight_reps'),
('Standing Single Leg Calf Raise','legs','calves',ARRAY[]::text[],'bodyweight','weight_reps'),
('Step Up','legs','quads',ARRAY['glutes'],'bodyweight','weight_reps'),
('Step Up (Barbell)','legs','quads',ARRAY['glutes'],'barbell','weight_reps'),
('Step Up (Dumbbell)','legs','quads',ARRAY['glutes'],'dumbbell','weight_reps'),
('Stiff Leg Deadlift (Barbell)','legs','hamstrings',ARRAY['glutes','lower back'],'barbell','weight_reps'),
('Stiff Leg Deadlift (Dumbbell)','legs','hamstrings',ARRAY['glutes','lower back'],'dumbbell','weight_reps'),
('Sumo Deadlift (Barbell)','legs','glutes',ARRAY['hamstrings','quads','lower back'],'barbell','weight_reps'),
('Sumo Deadlift (Smith Machine)','legs','glutes',ARRAY['hamstrings','quads'],'machine','weight_reps'),
('Sumo Squat (Barbell)','legs','quads',ARRAY['glutes','adductors'],'barbell','weight_reps'),
('Sumo Squat (Dumbbell)','legs','quads',ARRAY['glutes','adductors'],'dumbbell','weight_reps'),
('Sumo Squat (Smith Machine)','legs','quads',ARRAY['glutes','adductors'],'machine','weight_reps'),
('Wall Sit','legs','quads',ARRAY['glutes'],'bodyweight','time_reps'),
('Zercher Squat (Barbell)','legs','quads',ARRAY['glutes','hamstrings','core'],'barbell','weight_reps'),

-- CORE
('Ab Wheel Rollout','core','core',ARRAY['shoulders','lower back'],'other','weight_reps'),
('Chair Knee Raise','core','core',ARRAY['hip flexors'],'bodyweight','weight_reps'),
('Chair Leg Raise','core','core',ARRAY['hip flexors'],'bodyweight','weight_reps'),
('Cross Body Crunch','core','obliques',ARRAY['core'],'bodyweight','weight_reps'),
('Crunch','core','core',ARRAY[]::text[],'bodyweight','weight_reps'),
('Crunch (Cable)','core','core',ARRAY[]::text[],'cable','weight_reps'),
('Crunch (Machine)','core','core',ARRAY[]::text[],'machine','weight_reps'),
('Crunch (Stability Ball)','core','core',ARRAY[]::text[],'other','weight_reps'),
('Dead Bug Crunch','core','core',ARRAY['lower back'],'bodyweight','weight_reps'),
('Decline Crunch','core','core',ARRAY[]::text[],'bodyweight','weight_reps'),
('Decline Sit Up','core','core',ARRAY['hip flexors'],'bodyweight','weight_reps'),
('Flutter Kick','core','core',ARRAY['hip flexors'],'bodyweight','weight_reps'),
('Hanging Knee Raise','core','core',ARRAY['hip flexors'],'bodyweight','weight_reps'),
('Hanging Knee Raise Twist','core','obliques',ARRAY['hip flexors'],'bodyweight','weight_reps'),
('Hanging Leg Raise','core','core',ARRAY['hip flexors'],'bodyweight','weight_reps'),
('Hanging Leg Raise Twist','core','obliques',ARRAY['hip flexors'],'bodyweight','weight_reps'),
('Heel Touch','core','obliques',ARRAY['core'],'bodyweight','weight_reps'),
('Jackknife Sit Up','core','core',ARRAY['hip flexors'],'bodyweight','weight_reps'),
('L Sit Hold','core','core',ARRAY['hip flexors','triceps'],'bodyweight','time_reps'),
('Long Arm Crunch','core','core',ARRAY[]::text[],'bodyweight','weight_reps'),
('Lying Knee Raise','core','core',ARRAY['hip flexors'],'bodyweight','weight_reps'),
('Lying Leg Raise','core','core',ARRAY['hip flexors'],'bodyweight','weight_reps'),
('Oblique Crunch','core','obliques',ARRAY['core'],'bodyweight','weight_reps'),
('Plank','core','core',ARRAY['shoulders','lower back'],'bodyweight','time_reps'),
('Reverse Crunch','core','core',ARRAY['hip flexors'],'bodyweight','weight_reps'),
('Reverse Crunch (Cable)','core','core',ARRAY['hip flexors'],'cable','weight_reps'),
('Reverse Flutter Kick','core','core',ARRAY['glutes'],'bodyweight','weight_reps'),
('Reverse Plank','core','core',ARRAY['glutes','shoulders'],'bodyweight','time_reps'),
('Reverse Side Bend (Cable)','core','obliques',ARRAY['core'],'cable','weight_reps'),
('Reverse Woodchop (Cable)','core','obliques',ARRAY['core','shoulders'],'cable','weight_reps'),
('Russian Twist','core','obliques',ARRAY['core'],'bodyweight','weight_reps'),
('Seated In and Out','core','core',ARRAY['hip flexors'],'bodyweight','weight_reps'),
('Side Bend (Cable)','core','obliques',ARRAY[]::text[],'cable','weight_reps'),
('Side Bend (Dumbbell)','core','obliques',ARRAY[]::text[],'dumbbell','weight_reps'),
('Side Plank','core','obliques',ARRAY['core','shoulders'],'bodyweight','time_reps'),
('Sit Up','core','core',ARRAY['hip flexors'],'bodyweight','weight_reps'),
('Sit Up Twist','core','obliques',ARRAY['core'],'bodyweight','weight_reps'),
('Straight Arm Plank','core','core',ARRAY['shoulders','triceps'],'bodyweight','time_reps'),
('Torso Rotation (Cable)','core','obliques',ARRAY['core'],'cable','weight_reps'),
('Torso Rotation (Machine)','core','obliques',ARRAY['core'],'machine','weight_reps'),
('Tuck Up','core','core',ARRAY['hip flexors'],'bodyweight','weight_reps'),
('Windmill (Kettlebell)','core','obliques',ARRAY['core','shoulders'],'kettlebell','weight_reps'),
('Windshield Wiper','core','obliques',ARRAY['core'],'bodyweight','weight_reps'),
('Wood Chop (Cable)','core','obliques',ARRAY['core','shoulders'],'cable','weight_reps'),
('Wood Chop (Dumbbell)','core','obliques',ARRAY['core','shoulders'],'dumbbell','weight_reps'),

-- CARDIO
('Battle Rope','cardio','cardio',ARRAY['shoulders','core'],'other','time_distance'),
('Bicycle','cardio','cardio',ARRAY['quads','calves'],'other','time_distance'),
('Burpee','cardio','cardio',ARRAY['chest','shoulders','quads'],'bodyweight','weight_reps'),
('Butt Kicks','cardio','cardio',ARRAY['hamstrings','calves'],'bodyweight','time_distance'),
('Elliptical','cardio','cardio',ARRAY['quads','hamstrings','glutes'],'machine','time_distance'),
('Frogger','cardio','cardio',ARRAY['quads','core'],'bodyweight','time_distance'),
('High Knee Skip','cardio','cardio',ARRAY['quads','calves'],'bodyweight','time_distance'),
('Jump Rope','cardio','cardio',ARRAY['calves','shoulders'],'other','time_distance'),
('Jumping Jack','cardio','cardio',ARRAY['shoulders','calves'],'bodyweight','time_distance'),
('Lunge Jump','cardio','cardio',ARRAY['quads','glutes'],'bodyweight','weight_reps'),
('Mountain Climber','cardio','cardio',ARRAY['core','shoulders'],'bodyweight','time_distance'),
('Row','cardio','cardio',ARRAY['back','biceps'],'other','time_distance'),
('Rowing','cardio','cardio',ARRAY['back','biceps','legs'],'machine','time_distance'),
('Run','cardio','cardio',ARRAY['quads','hamstrings','calves'],'bodyweight','time_distance'),
('Sled Drag','cardio','cardio',ARRAY['hamstrings','glutes','back'],'other','time_distance'),
('Sled Push','cardio','cardio',ARRAY['quads','glutes','shoulders'],'other','time_distance'),
('Squat Jump','cardio','cardio',ARRAY['quads','glutes'],'bodyweight','weight_reps'),
('Stair Climber','cardio','cardio',ARRAY['quads','glutes','calves'],'machine','time_distance'),
('Stepper','cardio','cardio',ARRAY['quads','glutes','calves'],'machine','time_distance'),
('Swimming','cardio','cardio',ARRAY['back','shoulders','chest'],'bodyweight','time_distance'),
('Treadmill','cardio','cardio',ARRAY['quads','hamstrings','calves'],'machine','time_distance'),
('Tyre Flip','cardio','cardio',ARRAY['back','legs','shoulders'],'other','weight_reps'),

-- OLYMPIC
('Clean & Jerk','olympic','full body',ARRAY['quads','shoulders','traps','glutes'],'barbell','weight_reps'),
('Clean Deadlift','olympic','full body',ARRAY['hamstrings','glutes','lower back','traps'],'barbell','weight_reps'),
('Clean Pull','olympic','full body',ARRAY['traps','hamstrings','glutes'],'barbell','weight_reps'),
('Clean','olympic','full body',ARRAY['quads','shoulders','traps','glutes'],'barbell','weight_reps'),
('Hang Clean','olympic','full body',ARRAY['quads','shoulders','traps'],'barbell','weight_reps'),
('Hang Clean and Jerk','olympic','full body',ARRAY['quads','shoulders','traps'],'barbell','weight_reps'),
('Hang Power Clean','olympic','full body',ARRAY['quads','shoulders','traps'],'barbell','weight_reps'),
('Hang Snatch','olympic','full body',ARRAY['shoulders','traps','quads'],'barbell','weight_reps'),
('Muscle Snatch','olympic','full body',ARRAY['shoulders','traps'],'barbell','weight_reps'),
('Power Clean','olympic','full body',ARRAY['quads','shoulders','traps'],'barbell','weight_reps'),
('Power Snatch','olympic','full body',ARRAY['shoulders','traps','quads'],'barbell','weight_reps'),
('Push Jerk','olympic','full body',ARRAY['shoulders','triceps','quads'],'barbell','weight_reps'),
('Single Arm Dumbbell Jerk','olympic','full body',ARRAY['shoulders','quads'],'dumbbell','weight_reps'),
('Snatch Balance','olympic','full body',ARRAY['shoulders','quads','core'],'barbell','weight_reps'),
('Snatch Deadlift','olympic','full body',ARRAY['hamstrings','glutes','lower back','traps'],'barbell','weight_reps'),
('Snatch High Pull','olympic','full body',ARRAY['traps','shoulders','hamstrings'],'barbell','weight_reps'),
('Snatch Pull','olympic','full body',ARRAY['traps','hamstrings','glutes'],'barbell','weight_reps'),
('Snatch','olympic','full body',ARRAY['shoulders','traps','quads','hamstrings'],'barbell','weight_reps'),
('Squat Clean','olympic','full body',ARRAY['quads','glutes','shoulders','traps'],'barbell','weight_reps'),

-- FULL BODY
('Dead Hang','full_body','lats',ARRAY['forearms','biceps','core'],'bodyweight','time_reps'),
('Deadlift High Pull','full_body','full body',ARRAY['traps','shoulders','hamstrings','glutes'],'barbell','weight_reps'),
('Farmers Walk','full_body','full body',ARRAY['forearms','traps','core','quads'],'dumbbell','time_distance'),
('Gorilla Chin Crunch','full_body','lats',ARRAY['biceps','core'],'bodyweight','weight_reps'),
('Iron Cross (Dumbbell)','full_body','shoulders',ARRAY['chest','core'],'dumbbell','weight_reps'),
('Muscle Up','full_body','lats',ARRAY['chest','triceps','biceps'],'bodyweight','weight_reps'),
('Renegade Row (Dumbbell)','full_body','upper back',ARRAY['core','shoulders','biceps'],'dumbbell','weight_reps'),
('Slam Ball','full_body','full body',ARRAY['shoulders','core','quads'],'other','weight_reps'),
('Squat Row (Cable)','full_body','full body',ARRAY['quads','upper back','biceps'],'cable','weight_reps'),
('Swing (Kettlebell)','full_body','glutes',ARRAY['hamstrings','lower back','shoulders'],'kettlebell','weight_reps'),
('Thruster (Barbell)','full_body','full body',ARRAY['quads','shoulders','triceps'],'barbell','weight_reps'),
('Thruster (Kettlebell)','full_body','full body',ARRAY['quads','shoulders','triceps'],'kettlebell','weight_reps'),
('Turkish Get Up (Kettlebell)','full_body','full body',ARRAY['shoulders','core','quads'],'kettlebell','weight_reps'),
('Wall Ball','full_body','full body',ARRAY['quads','shoulders','core'],'other','weight_reps'),

-- NECK
('Lateral Neck Flexion','neck','neck',ARRAY[]::text[],'bodyweight','weight_reps'),
('Neck Curl','neck','neck',ARRAY[]::text[],'bodyweight','weight_reps'),
('Neck Extension','neck','neck',ARRAY[]::text[],'bodyweight','weight_reps'),
('Neck Flexion (Band)','neck','neck',ARRAY[]::text[],'other','weight_reps'),
('Neck Extension (Band)','neck','neck',ARRAY[]::text[],'other','weight_reps'),
('Neck Flexion (Plate)','neck','neck',ARRAY[]::text[],'other','weight_reps'),
('Neck Extension (Plate)','neck','neck',ARRAY[]::text[],'other','weight_reps'),
('Neck Harness Extension','neck','neck',ARRAY[]::text[],'other','weight_reps')

) as v(name, category, muscle_primary, muscle_secondary, equipment, logging_type)
where not exists (
  select 1 from exercises e where e.name = v.name
);
